language: generic

sudo: required

branches:
    only:
      - develop

services:
  - docker

install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker pull cogecomedia/cms-build
  #- ./bin/build.sh
  #- docker push cogecomedia/cms-build

script:
  - ./bin/run.sh test
  - ./bin/run.sh prod-browser

after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build -f Dockerfile.production -t cogecomedia/cms-service .;
      docker push cogecomedia/cms-service;
      wget -q -O - "https://gist.github.com/theomathieubhvr/8fea1ec233dd66373a42ebf3253f5b5f/raw/commit-changelog.sh" | bash;
    fi

notifications:
  slack: bhvr-bs:Momkig1fctiUVZHEOosGervO
